<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class FormativeMeasureResponsibleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('formative_measure_responsibles')->insert([
            [
                'id'=>1,
                'username'=>'Pedro Antonio Gómez Calderón',
                'misena_email'=>'pagomez6425@misena.edu.co',
                'institutional_email'=>'pagomezc@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10015246',
                'birthdate' => Carbon::parse('2020-05-06'),
                'phone'=>'3147554031',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>2,
                'username'=>'Santiago Bedoya',
                'misena_email'=>'sbedoya784@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1002656487',
                'birthdate' => Carbon::parse('2020-10-10'),
                'phone'=>'3043485901',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>14, // Apoyo Sennova
                'contract_type_id'=>5, // Provisional
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>3,
                'username'=>'Luis Evelio Martínez Arias',
                'misena_email'=>'luisevel@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'10231640',
                'birthdate' => Carbon::parse('2020-10-01'),
                'phone'=>'3017083660',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>4,
                'username'=>'Jose Alirio Londoño Rivera',
                'misena_email'=>'alonri@misena.edu.co',
                'institutional_email'=>'jalondo@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10241219',
                'birthdate' => Carbon::parse('2020-05-30'),
                'phone'=>'3104201527',
                'phone_ip'=>'3104201527',
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>5,
                'username'=>'Luis Alfredo Arias Moreno',
                'misena_email'=>'luis.arias.0@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'10241744',
                'birthdate' => Carbon::parse('2020-07-14'),
                'phone'=>'3208949370',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>6,
                'username'=>'Francisco Javier Vargas',
                'misena_email'=>'fjvargas@misena.edu.co',
                'institutional_email'=>'fjvargasf@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10243995',
                'birthdate' => Carbon::parse('2020-07-17'),
                'phone'=>'3105242307',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>7,
                'username'=>'Roberto Estrada Herrera',
                'misena_email'=>'restradah@misena.edu.co',
                'institutional_email'=>'restrada@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10248388',
                'birthdate' => Carbon::parse('2020-05-11'),
                'phone'=>'3002024140',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>8,
                'username'=>'Cesar Augusto Chica Palma',
                'misena_email'=>'chicapal@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'10261985',
                'birthdate' => Carbon::parse('2020-11-20'),
                'phone'=>'3113440161',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>9,
                'username'=>'José Fernando Vergara Gallego',
                'misena_email'=>'jfvergara@misena.edu.co',
                'institutional_email'=>'jfvergara@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10271981',
                'birthdate' => Carbon::parse('2020-04-15'),
                'phone'=>'3217068789',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>10,
                'username'=>'Guillermo Antonio Valencia Velásquez',
                'misena_email'=>'guivalen@misena.edu.co',
                'institutional_email'=>'gavalenciav@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10279010',
                'birthdate' => Carbon::parse('2020-04-15'),
                'phone'=>'3137656579',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>11,
                'username'=>'Jhon Freddy Cortés Soto',
                'misena_email'=>'jfrecos@misena.edu.co',
                'institutional_email'=>'jfcortess@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10279373',
                'birthdate' => Carbon::parse('2020-03-24'),
                'phone'=>'3103598404',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>12,
                'username'=>'Jhon Jairo Cárdenas Romero',
                'misena_email'=>'jotajota@misena.edu.co',
                'institutional_email'=>'jhoncardenas@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10279651',
                'birthdate' => Carbon::parse('2021-01-26'),
                'phone'=>'3117784659',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>13,
                'username'=>'German Rodríguez Valencia',
                'misena_email'=>'grodriguez86@misena.edu.co',
                'institutional_email'=>'gerodriguezv@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10285068',
                'birthdate' => Carbon::parse('2020-09-07'),
                'phone'=>'3152735162',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>14,
                'username'=>'Jaime Giraldo Orrego',
                'misena_email'=>'jagio13@misena.edu.co',
                'institutional_email'=>'Jgiraldo@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'10286761',
                'birthdate' => Carbon::parse('2020-11-30'),
                'phone'=>'3136443404',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>15,
                'username'=>'Jorge Armando Ospina Bedoya',
                'misena_email'=>'jorge28868@hotmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1053766410',
                'birthdate' => Carbon::parse('2020-06-12'),
                'phone'=>'3217173886',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>16,
                'username'=>'Carlos Mario Rocha Osorio',
                'misena_email'=>'cmrochaos3@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1053782693',
                'birthdate' => Carbon::parse('2020-04-01'),
                'phone'=>'3136628957',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>17,
                'username'=>'Jhonatan Franco Arias',
                'misena_email'=>'eltaja@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1053784021',
                'birthdate' => Carbon::parse('2020-03-01'),
                'phone'=>'3117848943',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>18,
                'username'=>'Santiago Becerra Henao',
                'misena_email'=>'sanbehe@misena.edu.co',
                'institutional_email'=>'sbecerrah@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'1053784950',
                'birthdate' => Carbon::parse('2020-02-18'),
                'phone'=>'3117541813',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>19,
                'username'=>'Luisa Fernanda López Arroyave',
                'misena_email'=>'luifelopez@sena.edu.co',
                'institutional_email'=>'luifelopez@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'1053799233',
                'birthdate' => Carbon::parse('2020-12-14'),
                'phone'=>'3103941899',
                'phone_ip'=>'62442',
                'gender'=>'F',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>20,
                'username'=>'Asdrúbal Gómez Galeano',
                'misena_email'=>'agomez296@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1053800692',
                'birthdate' => Carbon::parse('2021-01-01'),
                'phone'=>'3128820955',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>21,
                'username'=>'Jeyson Leir Soto Cardona',
                'misena_email'=>'jeisonsoto3d@misena.edu.co',
                'institutional_email'=>'jlsotoc@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'1053801927',
                'birthdate' => Carbon::parse('2020-04-08'),
                'phone'=>'3008935423',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>23, // Instructor Planta temporal
                'contract_type_id'=>4, // Planta Temporal
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>22,
                'username'=>'Guillermo Andrés Villegas',
                'misena_email'=>'2983@misena.edu.co',
                'institutional_email'=>'2983@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'1053803892',
                'birthdate' => Carbon::parse('2020-06-29'),
                'phone'=>'3156089663',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>23,
                'username'=>'Yaneth Mejía Rendón',
                'misena_email'=>'ymejia624@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1053811426',
                'birthdate' => Carbon::parse('2020-04-03'),
                'phone'=>'3045458490',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>24,
                'username'=>'Carolina Giraldo Restrepo',
                'misena_email'=>'fedpaz13@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1054920080',
                'birthdate' => Carbon::parse('2020-03-21'),
                'phone'=>'3128318026',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>25,
                'username'=>'Yovert Edwin Ussa López',
                'misena_email'=>'yovert2102@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1061532086',
                'birthdate' => Carbon::parse('2020-03-21'),
                'phone'=>'3233375665',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>26,
                'username'=>'Duber Ortiz Beltrán',
                'misena_email'=>'dortizb91@misena.edu.co',
                'institutional_email'=>'sstasesoramos@gmail.com',
                'document_type'=>'CC',
                'document'=>'1083894002',
                'birthdate' => Carbon::parse('2020-03-21'),
                'phone'=>'3142541067',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>20, // Instructor contratista - TSA
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>27,
                'username'=>'Luis Camilo Estrada Patiño',
                'misena_email'=>'camiloestrada@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1085297027',
                'birthdate' => Carbon::parse('2020-06-24'),
                'phone'=>'3128488679',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>28,
                'username'=>'Juan Sebastián Hurtado Ramírez',
                'misena_email'=>'juansebastianhurtadoramirez@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'1093221371',
                'birthdate' => Carbon::parse('2020-05-19'),
                'phone'=>'3113767180',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>29,
                'username'=>'Jaime Adolfo Fuentes Sánchez',
                'misena_email'=>'adolfofuentes@misena.edu.co',
                'institutional_email'=>'adolfofuentes@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'11224476',
                'birthdate' => Carbon::parse('2020-04-16'),
                'phone'=>'3008115106',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>30,
                'username'=>'Luis Enrique Bravo Cardona',
                'misena_email'=>'lebravocardona@misena.edu.co',
                'institutional_email'=>'lebravoc@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'15903478',
                'birthdate' => Carbon::parse('2020-03-26'),
                'phone'=>'3137485587',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>31,
                'username'=>'Jhon Fredy García Pineda',
                'misena_email'=>'jfgarcia62@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'16070726',
                'birthdate' => Carbon::parse('2020-05-17'),
                'phone'=>'3218517820',
                'phone_ip'=>'62169',
                'gender'=>'M',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>32,
                'username'=>'Álvaro Osorio Galeano',
                'misena_email'=>'arqtkalosga@gmail.com',
                'institutional_email'=>'alosoriog@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'16071354',
                'birthdate' => Carbon::parse('2020-04-30'),
                'phone'=>'3117615075',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>33,
                'username'=>'Camilo Andrés Arango',
                'misena_email'=>'camiaramo@misena.edu.co',
                'institutional_email'=>'camiaramo@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'16077061',
                'birthdate' => Carbon::parse('2020-09-08'),
                'phone'=>'3003929427',
                'phone_ip'=>'0',
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>34,
                'username'=>'Consuelo García Escobar',
                'misena_email'=>'cgarciae@misena.edu.co',
                'institutional_email'=>'cgarciae@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'24318223',
                'birthdate' => Carbon::parse('2021-01-18'),
                'phone'=>'3113076751',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>35,
                'username'=>'Carmen Elena Hernández Rincón',
                'misena_email'=>'carelena@misena.edu.co',
                'institutional_email'=>'cehernandezr@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'24340753',
                'birthdate' => Carbon::parse('2020-06-07'),
                'phone'=>'3147917762',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>36,
                'username'=>'Luz De Fátima Álvarez Osorio',
                'misena_email'=>'lfalvarez@misena.edu.co',
                'institutional_email'=>'lfalvarezo@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'25232397',
                'birthdate' => Carbon::parse('2020-06-13'),
                'phone'=>'3113851917',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>37,
                'username'=>'Blanca Iris Murillo Arenas',
                'misena_email'=>'blancairis@misena.edu.co',
                'institutional_email'=>'blancairismurillo538@gmail.com',
                'document_type'=>'CC',
                'document'=>'25234375',
                'birthdate' => Carbon::parse('2020-07-26'),
                'phone'=>'3103475206',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>38,
                'username'=>'Luisa Fernanda Cardona Vargas',
                'misena_email'=>'luisa.cardona26@gmail.com',
                'institutional_email'=>'lcardonava@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'30236108',
                'birthdate' => Carbon::parse('2020-09-02'),
                'phone'=>'3207810113',
                'phone_ip'=>'62442',
                'gender'=>'F',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>39,
                'username'=>'Ángela Maria Cuervo Valencia',
                'misena_email'=>'angela.cuervo@misena.edu.co',
                'institutional_email'=>'acuervo@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'30236155',
                'birthdate' => Carbon::parse('2020-09-25'),
                'phone'=>'3015716884',
                'phone_ip'=>'62006',
                'gender'=>'F',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>40,
                'username'=>'Maria Beatriz Pava Hurtado',
                'misena_email'=>'bpava@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'30270825',
                'birthdate' => Carbon::parse('2021-01-16'),
                'phone'=>'3162559047',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>41,
                'username'=>'Ruby Vargas Ruiz',
                'misena_email'=>'ruvaruiz@misena.edu.co',
                'institutional_email'=>'rvargasr@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'30292725',
                'birthdate' => Carbon::parse('2020-02-20'),
                'phone'=>'3168756222',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>23, // Instructor Planta temporal
                'contract_type_id'=>5, // Provisional
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>42,
                'username'=>'Lucila Noreña Arias',
                'misena_email'=>'lucilanorarias@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'30310215',
                'birthdate' => Carbon::parse('2020-06-06'),
                'phone'=>'3176422121',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>19, // Instructor contratista - Desplazados
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>43,
                'username'=>'Luz Stella Soto Alzate',
                'misena_email'=>'stellasoto@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'30322795',
                'birthdate' => Carbon::parse('2020-08-26'),
                'phone'=>'3207379363',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>44,
                'username'=>'Sandra Milena Trujillo Ortiz',
                'misena_email'=>'smtrujillo@misena.edu.co',
                'institutional_email'=>'smtrujillo@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'30336710',
                'birthdate' => Carbon::parse('2020-11-03'),
                'phone'=>'3108491154',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>45,
                'username'=>'Lorena Patricia Valencia',
                'misena_email'=>'valencia.lp@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'30338297',
                'birthdate' => Carbon::parse('2020-05-19'),
                'phone'=>'3176171144',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>46,
                'username'=>'Ángela Marcela Castellanos Ortegón',
                'misena_email'=>'amcastellanoso@gmail.com',
                'institutional_email'=>'amcastellanoso@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'30398681',
                'birthdate' => Carbon::parse('2020-07-20'),
                'phone'=>'3008948200',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>47,
                'username'=>'Verónica Bedoya Marín',
                'misena_email'=>'vbedoyam@sena.edu.co',
                'institutional_email'=>'vbedoyam@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'30399080',
                'birthdate' => Carbon::parse('2021-01-02'),
                'phone'=>'3136861662',
                'phone_ip'=>'62070',
                'gender'=>'F',
                'position_id'=>12, // Apoyo Bienestar al aprendiz
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>48,
                'username'=>'Andrea Del Pilar Álvarez Camargo',
                'misena_email'=>'adalvarez40@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'30405204',
                'birthdate' => Carbon::parse('2021-11-14'),
                'phone'=>'3146611226',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>20, // Instructor contratista - TSA
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>49,
                'username'=>'Alexandra Naranjo Cardona',
                'misena_email'=>'alexa_nc@misena.edu.co',
                'institutional_email'=>'alexa_nc@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'31321612',
                'birthdate' => Carbon::parse('2020-06-07'),
                'phone'=>'3135217056',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>50,
                'username'=>'Nancy Stella Quintero Ocampo',
                'misena_email'=>'nancyq@misena.edu.co',
                'institutional_email'=>'nancyq@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'41922785',
                'birthdate' => Carbon::parse('2020-08-14'),
                'phone'=>'3188732360',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>51,
                'username'=>'Ángela Patricia Muñoz Alvarado',
                'misena_email'=>'angela_ma@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'41933186',
                'birthdate' => Carbon::parse('2020-08-02'),
                'phone'=>'3135180441',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>52,
                'username'=>'Beatriz Elena Sepúlveda López',
                'misena_email'=>'beasepulveda@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'42135428',
                'birthdate' => Carbon::parse('2020-12-01'),
                'phone'=>'3005668382',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>53,
                'username'=>'Adriana Rodríguez Morales',
                'misena_email'=>'arodriguez949@misena.edu.co',
                'institutional_email'=>'adrrodriguez@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'51808949',
                'birthdate' => Carbon::parse('2020-05-11'),
                'phone'=>'3176366444',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>23, // Instructor Planta temporal
                'contract_type_id'=>4, // Planta Temporal
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>54,
                'username'=>'Diana Milena Gómez Tabares',
                'misena_email'=>'dianam.gomezt@misena.edu.co',
                'institutional_email'=>'dmgomezt@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'66872571',
                'birthdate' => Carbon::parse('2020-04-14'),
                'phone'=>'3183908071',
                'phone_ip'=>null,
                'gender'=>'F',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>55,
                'username'=>'Ricardo Antonio López Arias',
                'misena_email'=>'rala71@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'75062920',
                'birthdate' => Carbon::parse('2020-02-17'),
                'phone'=>'3116202223',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>56,
                'username'=>'Carlos Duber Villa González',
                'misena_email'=>'carlosduber@gmail.com',
                'institutional_email'=>'cdvilla8@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'75064088',
                'birthdate' => Carbon::parse('2020-07-23'),
                'phone'=>'3165532410',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>57,
                'username'=>'Leonardo Fabio Sánchez Montoya',
                'misena_email'=>'leofasa171@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'75078052',
                'birthdate' => Carbon::parse('2020-03-17'),
                'phone'=>'3168658117',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>58,
                'username'=>'Andrés Mauricio Jaramillo González',
                'misena_email'=>'anmajago@misena.edu.co',
                'institutional_email'=>'ajaramillog@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75081636',
                'birthdate' => Carbon::parse('2020-11-23'),
                'phone'=>'3113837172',
                'phone_ip'=>'63201',
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>59,
                'username'=>'Dairo De Jesús Gañán Gallo',
                'misena_email'=>'dairog@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'75089861',
                'birthdate' => Carbon::parse('2020-03-20'),
                'phone'=>'3104466876',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>60,
                'username'=>'Andrés Felipe López Chica',
                'misena_email'=>'aflopez978@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'75090879',
                'birthdate' => Carbon::parse('2020-06-26'),
                'phone'=>'3206874025',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>61,
                'username'=>'Aparicio Mejía Rendón',
                'misena_email'=>'apariciomejia@misena.edu.co',
                'institutional_email'=>'apmejiar@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75091846',
                'birthdate' => Carbon::parse('2020-07-29'),
                'phone'=>'3205792842',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>62,
                'username'=>'Diego Andrés Serna Velásquez',
                'misena_email'=>'daserna99@misena.edu.co',
                'institutional_email'=>'dasernav@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75096299',
                'birthdate' => Carbon::parse('2020-11-21'),
                'phone'=>'3146504873',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>63,
                'username'=>'Diego Alexander Grajales Pérez',
                'misena_email'=>'dagrajales@misena.edu.co',
                'institutional_email'=>'dagrajales@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75096903',
                'birthdate' => Carbon::parse('2020-03-12'),
                'phone'=>'3158368667',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>64,
                'username'=>'Andrés Julián Hoyos Caicedo',
                'misena_email'=>'ajhoyos@misena.edu.co',
                'institutional_email'=>'ajhoyos@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'75097575',
                'birthdate' => Carbon::parse('2020-04-28'),
                'phone'=>'3107324131',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>21, // Instructor contratista - virtual
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>65,
                'username'=>'Roland Roth Echeverry',
                'misena_email'=>'rolyroth@misena.edu.co',
                'institutional_email'=>'rorothe@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75103320',
                'birthdate' => Carbon::parse('2021-01-09'),
                'phone'=>'3142593425',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>23, // Instructor Planta temporal
                'contract_type_id'=>4, // Planta Temporal
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>66,
                'username'=>'Julián Humberto Salazar Pineda',
                'misena_email'=>'Jusapi824@misena.edu.co',
                'institutional_email'=>'jsalazar@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'75106549',
                'birthdate' => Carbon::parse('2020-10-07'),
                'phone'=>'3113778657',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>67,
                'username'=>'Alexander García Vásquez',
                'misena_email'=>'agarciavasquez@misena.edu.co',
                'institutional_email'=>'agarciavasquez@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'7684828',
                'birthdate' => Carbon::parse('2020-04-18'),
                'phone'=>'3148515827',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>68,
                'username'=>'Juan Carlos Arango',
                'misena_email'=>'jcarango@misena.edu.co',
                'institutional_email'=>'jcarango@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'79274609',
                'birthdate' => Carbon::parse('2020-04-08'),
                'phone'=>'3137169379',
                'phone_ip'=>'62301',
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>69,
                'username'=>'Roberto José Amaya Ibáñez',
                'misena_email'=>'ramaya@misena.edu.co',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'79453909',
                'birthdate' => Carbon::parse('2020-07-26'),
                'phone'=>'3123932040',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>18, // Instructor contratista - Articulada
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>70,
                'username'=>'Javier Ariza Useche',
                'misena_email'=>'javier.ariza@misena.edu.co',
                'institutional_email'=>'jarizau@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'79836769',
                'birthdate' => Carbon::parse('2020-04-04'),
                'phone'=>'3185272465',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>71,
                'username'=>'José Daniel Cano Osorio',
                'misena_email'=>'jdanielco@misena.edu.co',
                'institutional_email'=>'jdcano@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'79848867',
                'birthdate' => Carbon::parse('2020-05-13'),
                'phone'=>'3004118202',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>72,
                'username'=>'Federico Murcia Ríos',
                'misena_email'=>'ficomurc@gmail.com',
                'institutional_email'=>'fmurcia8@misena.edu.co',
                'document_type'=>'CC',
                'document'=>'80882748',
                'birthdate' => Carbon::parse('2020-09-14'),
                'phone'=>'3208749896',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>73,
                'username'=>'Jaime Orlando Agreda Sijindioy',
                'misena_email'=>'jaime.agredas@gmail.com',
                'institutional_email'=>null,
                'document_type'=>'CC',
                'document'=>'97472782',
                'birthdate' => Carbon::parse('2020-03-16'),
                'phone'=>'3183944196',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>74,
                'username'=>'Victor Mauricio Acevedo Correa',
                'misena_email'=>'vmacevedo@misena.edu.co',
                'institutional_email'=>'vacevedo@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'9817289',
                'birthdate' => Carbon::parse('2020-06-22'),
                'phone'=>'3137086769',
                'phone_ip'=>'62301',
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>75,
                'username'=>'Fernando Arciniegas Córdoba',
                'misena_email'=>'fernandoac@misena.edu.co',
                'institutional_email'=>'farciniegas@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'98392877',
                'birthdate' => Carbon::parse('2020-03-13'),
                'phone'=>'3162860686',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>22, // Instructor de carrera administrativa
                'contract_type_id'=>1, // Carrera Administrativa
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ],
            [
                'id'=>76,
                'username'=>'Oscar Fernando Aristizabal Cardona',
                'misena_email'=>'ofac@misena.edu.co',
                'institutional_email'=>'oaristizabal@sena.edu.co',
                'document_type'=>'CC',
                'document'=>'9859602',
                'birthdate' => Carbon::parse('2020-11-17'),
                'phone'=>'3103972370',
                'phone_ip'=>null,
                'gender'=>'M',
                'position_id'=>17, // Instructor contratista
                'contract_type_id'=>2, // Contratista
                'type'=>'Instructor',
                'photo'=>null,
                'state'=>'Activo',
            ]
        ]);
    }
}
